name: sample wf

on: 
  issues: 
    types: [opened, edited]
  #push:
  #repository_dispatch:
  
jobs:
  shell:
    runs-on: ubuntu-latest

    steps:
      - name: run commands
        run: |
          pwd
          node -v
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Comment for getting approval
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
            issue_number: "${{github.event.issue.number}}",
            owner: "${{github.repository_owner}}",
            repo: "${{github.event.repository.name}}",
            body: "Thanks for opening issue!! Please wait until the approvers approve"
            })
      - name: Chekout
        uses: actions/checkout@v2
      - name: Body
        env:
          from_event: "${{ github.event.issue.body }}"
        run: |
          #echo $from_event
          body=$(python ./scripts/details.py $from_event)
          echo "customer_name=$(echo $body | cut -d "|" -f 1)" >> $GITHUB_ENV
          echo "init_user=$(echo $body | cut -d "|" -f 2)" >> $GITHUB_ENV
      - name: Display 
        run: |
          echo $customer_name
          echo $init_user
      - name: Comment for getting approval
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
            issue_number: "${{github.event.issue.number}}",
            owner: "${{github.repository_owner}}",
            repo: "${{github.event.repository.name}}",
            body: "The request is to create tenant for $customer_name having initial user as $init_user. Please comment `/approve`, if you are an approver"
            })
        
