name: sample wf

on: 
  issues: 
    types: [opened, edited]
  issue_comment:
    types: [created]
  #push:
  #repository_dispatch:
  
jobs:
  issue-creation:
    if: ( github.event_name == 'issues' && github.event.action == 'opened' )
    runs-on: ubuntu-latest
    outputs:
      customer_name: ${{ steps.set_output.outputs.data1 }}
      init_user: ${{ steps.set_output.outputs.data2 }}
    steps: 
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Welcome message
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
            issue_number: "${{github.event.issue.number}}",
            owner: "${{github.repository_owner}}",
            repo: "${{github.event.repository.name}}",
            body: "Thanks for opening issue!! Please wait until the approvers approve"
            })
      - name: Chekout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Body
        env:
          from_event: "${{ github.event.issue.body }}"
        run: |
          #echo $from_event
          body=$(python ./scripts/details.py $from_event)
          echo "customer_name=$(echo $body | cut -d "|" -f 1)" >> $GITHUB_ENV
          echo "init_user=$(echo $body | cut -d "|" -f 2)" >> $GITHUB_ENV
      - name: Set output
        id: set_output
        run: |
          echo $customer_name
          echo $init_user
          echo "::set-output name=data1::$customer_name"
          echo "::set-output name=data2::$init_user"
      - name: Comment for getting approval
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
            issue_number: "${{github.event.issue.number}}",
            owner: "${{github.repository_owner}}",
            repo: "${{github.event.repository.name}}",
            body: "Please review and comment `/approve`, if you are an approver"
            })
  approval-comment:
    if: ( github.event_name == 'issue_comment' )
    runs-on: ubuntu-latest
    #needs: issue-creation
    #env: 
      #customer_name: ${{ needs.issue-creation.outputs.customer_name}}
      #init_user: ${{ needs.issue-creation.outputs.init_user}}
    steps:
      - name: Display 
        run: |
          echo $customer_name
          echo $init_user
      - name: Checking approval comment
        run: |
          python ./scripts/check-approver.py ${{ github.triggering_actor }}
            - if: ( github.event_name == 'issues' && github.event.action == 'opened' )
