name: sample wf

on: push

jobs:
  shell:
    runs-on: ubuntu-latest

    steps:
      - name: run commands
        run: |
          pwd
          node -v
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
