name: sample wf

on: 
  issues: 
    types: [opened, edited]
  push:
  repository_dispatch:
  
jobs:
  shell:
    runs-on: ubuntu-latest

    steps:
      - name: run commands
        run: |
          pwd
          node -v
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Chekout
        uses: actions/checkout@v2
      - name: Body
        run: |
          python --version
        
