name: sample wf

on: 
  issues: 
    types: [opened, edited]
  issue_comment:
    types: [created]
  #push:
  #repository_dispatch:
  
jobs:
  tenant-creation:
    runs-on: ubuntu-latest
    steps:
      - if: ( github.event_name == 'issues' && github.event.action == 'opened' )
        name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
      - if: ( github.event_name == 'issues' && github.event.action == 'opened' )
        name: Welcome message
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
            issue_number: "${{github.event.issue.number}}",
            owner: "${{github.repository_owner}}",
            repo: "${{github.event.repository.name}}",
            body: "Thanks for opening issue!! Please wait until the approvers approve"
            })
      - if: ( github.event_name == 'issues' && github.event.action == 'opened' )
        name: Chekout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - if: ( github.event_name == 'issues' && github.event.action == 'opened' )
        name: Body
        env:
          from_event: "${{ github.event.issue.body }}"
        run: |
          #echo $from_event
          body=$(python ./scripts/details.py $from_event)
          echo "customer_name=$(echo $body | cut -d "|" -f 1)" >> $GITHUB_ENV
          echo "init_user=$(echo $body | cut -d "|" -f 2)" >> $GITHUB_ENV
      - if: ( github.event_name == 'issues' && github.event.action == 'opened' )
        name: Display 
        run: |
          echo $customer_name
          echo $init_user
      - if: ( github.event_name == 'issues' && github.event.action == 'opened' )
        name: Comment for getting approval
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
            issue_number: "${{github.event.issue.number}}",
            owner: "${{github.repository_owner}}",
            repo: "${{github.event.repository.name}}",
            body: "Please review and comment `/approve`, if you are an approver"
            })
      - if: ( github.event_name == 'issue_comment' && github.event.action == 'created' && github.event.comment.body == '/approve' )
        name: Checking approvval comment
        run: |
          python ./scripts/check-approver.py ${{ github.triggering_actor }}
            - if: ( github.event_name == 'issues' && github.event.action == 'opened' )
      - if: ( github.event_name == 'issue_comment' && github.event.action == 'created' && github.event.comment.body == '/approve' )
        name: Display 
        run: |
          echo $customer_name
          echo $init_user
