name: Create Tenant

on:
  issues:
    types: [opened,reopened]
  issue_comment:
    types: [created]
  push: 

jobs:
  corestack:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
