name: Create Tenant

on:
  issues:
    types: [opened,reopened]
  issue_comment:
    types: [created]
  push: 

jobs:
  corestack:
    runs-on: ubuntu-latest
    steps:
      - name: Get Issue
        id: get_issue
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.get({
            issue_number: "1",
            owner: "${{github.repository_owner}}",
            repo: "github-actions"
            })
      - name: get from api
        run: |
          curl -L -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.TOKEN }}" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/anil1412/github-actions/issues/1 | jq '.body'
      - name: Token
        run: echo "${{ secrets.TOKEN }}"
